// Auto-generated skill aliases mapping from skills.json (Curated strictly with custom overrides)
export const COMMON_SKILL_ALIASES: Record<string, string> = {
    'activemq': 'ActiveMQ',
    'actix web': 'Actix Web',
    'actix-web': 'Actix Web',
    'actixweb': 'Actix Web',
    'adobe xd': 'Adobe XD',
    'adobe-xd': 'Adobe XD',
    'adobexd': 'Adobe XD',
    'alchemy, infura': 'Alchemy, Infura',
    'alchemy,-infura': 'Alchemy, Infura',
    'alchemyinfura': 'Alchemy, Infura',
    'algolia & meilisearch': 'Algolia & Meilisearch',
    'algolia and meilisearch': 'Algolia & Meilisearch',
    'algolia meilisearch': 'Algolia & Meilisearch',
    'algolia-&-meilisearch': 'Algolia & Meilisearch',
    'algoliameilisearch': 'Algolia & Meilisearch',
    'algorithms': 'Algorithms',
    'amqp': 'AMQP',
    'anchor': 'Anchor',
    'android sdk': 'Android SDK',
    'android-sdk': 'Android SDK',
    'androidsdk': 'Android SDK',
    'angular': 'Angular',
    'ansible': 'Ansible',
    'ant design': 'Ant Design',
    'ant-design': 'Ant Design',
    'antdesign': 'Ant Design',
    'anthropic claude': 'Anthropic Claude',
    'anthropic-claude': 'Anthropic Claude',
    'anthropicclaude': 'Anthropic Claude',
    'apache airflow': 'Apache Airflow',
    'apache cassandra': 'Apache Cassandra',
    'apache hadoop': 'Apache Hadoop',
    'apache http server': 'Apache HTTP Server',
    'apache kafka': 'Apache Kafka',
    'apache pulsar': 'Apache Pulsar',
    'apache spark': 'Apache Spark',
    'apache-airflow': 'Apache Airflow',
    'apache-cassandra': 'Apache Cassandra',
    'apache-hadoop': 'Apache Hadoop',
    'apache-http-server': 'Apache HTTP Server',
    'apache-kafka': 'Apache Kafka',
    'apache-pulsar': 'Apache Pulsar',
    'apache-spark': 'Apache Spark',
    'apacheairflow': 'Apache Airflow',
    'apachecassandra': 'Apache Cassandra',
    'apachehadoop': 'Apache Hadoop',
    'apachehttpserver': 'Apache HTTP Server',
    'apachekafka': 'Apache Kafka',
    'apachepulsar': 'Apache Pulsar',
    'apachespark': 'Apache Spark',
    'api gateway pattern': 'API Gateway Pattern',
    'api-gateway-pattern': 'API Gateway Pattern',
    'apigatewaypattern': 'API Gateway Pattern',
    'apollo client': 'Apollo Client',
    'apollo server': 'Apollo Server',
    'apollo-client': 'Apollo Client',
    'apollo-server': 'Apollo Server',
    'apolloclient': 'Apollo Client',
    'apolloserver': 'Apollo Server',
    'apple push notification service': 'Apple Push Notification Service',
    'apple-push-notification-service': 'Apple Push Notification Service',
    'applepushnotificationservice': 'Apple Push Notification Service',
    'appwrite': 'Appwrite',
    'appwrite-supabase': 'Appwrite',
    'appwritsupabase': 'Appwrite',
    'arbitrum': 'Arbitrum',
    'arch linux': 'Arch Linux',
    'arch-linux': 'Arch Linux',
    'archlinux': 'Arch Linux',
    'argocd': 'ArgoCD',
    'arrays': 'Arrays',
    'artificial intelligence': 'Artificial Intelligence',
    'artificial-intelligence': 'Artificial Intelligence',
    'artificialintelligence': 'Artificial Intelligence',
    'asp.net': 'ASP.NET',
    'asp.net-core': 'ASP.NET',
    'aspnet': 'ASP.NET',
    'assembly': 'Assembly',
    'athena': 'Athena',
    'augmented reality': 'Augmented Reality',
    'augmented-reality': 'Augmented Reality',
    'augmentedreality': 'Augmented Reality',
    'auth0': 'Auth0',
    'auth0 authentication': 'Auth0',
    'auth0-authentication': 'Auth0',
    'auth0authentication': 'Auth0',
    'avl': 'AVL',
    'aws': 'AWS',
    'aws batch': 'AWS Batch',
    'aws cloudformation': 'AWS CloudFormation',
    'aws cloudfront cdn': 'AWS CloudFront CDN',
    'aws cloudwatch': 'AWS CloudWatch',
    'aws cognito': 'AWS Cognito',
    'aws dynamodb': 'AWS DynamoDB',
    'aws ec2': 'AWS EC2',
    'aws ecs': 'AWS ECS',
    'aws eks': 'AWS EKS',
    'aws elastic beanstalk': 'AWS Elastic Beanstalk',
    'aws elasticache': 'AWS ElastiCache',
    'aws eventbridge': 'AWS EventBridge',
    'aws iam': 'AWS IAM',
    'aws kinesis data streams': 'AWS Kinesis Data Streams',
    'aws lambda': 'AWS Lambda',
    'aws rds': 'AWS RDS',
    'aws route 53': 'AWS Route 53',
    'aws route 53 dns': 'AWS Route 53 DNS',
    'aws s3': 'AWS S3',
    'aws secrets manager': 'AWS Secrets Manager',
    'aws sns': 'AWS SNS',
    'aws sqs': 'AWS SQS',
    'aws step functions': 'AWS Step Functions',
    'aws vpc': 'AWS VPC',
    'aws-batch': 'AWS Batch',
    'aws-cloudformation': 'AWS CloudFormation',
    'aws-cloudfront-cdn': 'AWS CloudFront CDN',
    'aws-cloudwatch': 'AWS CloudWatch',
    'aws-cognito': 'AWS Cognito',
    'aws-dynamodb': 'AWS DynamoDB',
    'aws-ec2': 'AWS EC2',
    'aws-ecs': 'AWS ECS',
    'aws-eks': 'AWS EKS',
    'aws-elastic-beanstalk': 'AWS Elastic Beanstalk',
    'aws-elasticache': 'AWS ElastiCache',
    'aws-eventbridge': 'AWS EventBridge',
    'aws-iam': 'AWS IAM',
    'aws-kinesis-data-streams': 'AWS Kinesis Data Streams',
    'aws-lambda': 'AWS Lambda',
    'aws-rds': 'AWS RDS',
    'aws-route-53': 'AWS Route 53',
    'aws-route-53-dns': 'AWS Route 53 DNS',
    'aws-s3': 'AWS S3',
    'aws-secrets-manager': 'AWS Secrets Manager',
    'aws-sns': 'AWS SNS',
    'aws-sqs': 'AWS SQS',
    'aws-step-functions': 'AWS Step Functions',
    'aws-vpc': 'AWS VPC',
    'awsbatch': 'AWS Batch',
    'awscloudformation': 'AWS CloudFormation',
    'awscloudfrontcdn': 'AWS CloudFront CDN',
    'awscloudwatch': 'AWS CloudWatch',
    'awscognito': 'AWS Cognito',
    'awsdynamodb': 'AWS DynamoDB',
    'awsec2': 'AWS EC2',
    'awsecs': 'AWS ECS',
    'awseks': 'AWS EKS',
    'awselasticache': 'AWS ElastiCache',
    'awselasticbeanstalk': 'AWS Elastic Beanstalk',
    'awseventbridge': 'AWS EventBridge',
    'awsiam': 'AWS IAM',
    'awskinesisdatastreams': 'AWS Kinesis Data Streams',
    'awslambda': 'AWS Lambda',
    'awsrds': 'AWS RDS',
    'awsroute53': 'AWS Route 53',
    'awsroute53dns': 'AWS Route 53 DNS',
    'awss3': 'AWS S3',
    'awssecretsmanager': 'AWS Secrets Manager',
    'awssns': 'AWS SNS',
    'awssqs': 'AWS SQS',
    'awsstepfunctions': 'AWS Step Functions',
    'awsvpc': 'AWS VPC',
    'axum': 'Axum',
    'azure active directory': 'Azure Active Directory',
    'azure app service': 'Azure App Service',
    'azure blob storage': 'Azure Blob Storage',
    'azure cosmos db': 'Azure Cosmos DB',
    'azure devops': 'Azure DevOps',
    'azure event grid': 'Azure Event Grid',
    'azure functions': 'Azure Functions',
    'azure kubernetes service (aks)': 'Azure Kubernetes Service (AKS)',
    'azure service bus': 'Azure Service Bus',
    'azure sql database': 'Azure SQL Database',
    'azure-active-directory': 'Azure Active Directory',
    'azure-app-service': 'Azure App Service',
    'azure-blob-storage': 'Azure Blob Storage',
    'azure-cosmos-db': 'Azure Cosmos DB',
    'azure-devops': 'Azure DevOps',
    'azure-event-grid': 'Azure Event Grid',
    'azure-functions': 'Azure Functions',
    'azure-kubernetes-service-(aks)': 'Azure Kubernetes Service (AKS)',
    'azure-service-bus': 'Azure Service Bus',
    'azure-sql-database': 'Azure SQL Database',
    'azureactivedirectory': 'Azure Active Directory',
    'azureappservice': 'Azure App Service',
    'azureblobstorage': 'Azure Blob Storage',
    'azurecosmosdb': 'Azure Cosmos DB',
    'azuredevops': 'Azure DevOps',
    'azureeventgrid': 'Azure Event Grid',
    'azurefunctions': 'Azure Functions',
    'azurekubernetesserviceaks': 'Azure Kubernetes Service (AKS)',
    'azureservicebus': 'Azure Service Bus',
    'azuresqldatabase': 'Azure SQL Database',
    'b trees': 'B-Trees',
    'b-trees': 'B-Trees',
    'babel': 'Babel',
    'backend driven frontend': 'Backend-Driven Frontend',
    'backend for frontend': 'Backend for Frontend',
    'backend-driven frontend': 'Backend-Driven Frontend',
    'backend-driven-frontend': 'Backend-Driven Frontend',
    'backend-for-frontend': 'Backend for Frontend',
    'backenddrivenfrontend': 'Backend-Driven Frontend',
    'backendforfrontend': 'Backend for Frontend',
    'backtracking': 'Backtracking',
    'bash': 'Bash',
    'bazel': 'Bazel',
    'bellman ford algorithm': 'Bellman-Ford Algorithm',
    'bellman-ford algorithm': 'Bellman-Ford Algorithm',
    'bellman-ford-algorithm': 'Bellman-Ford Algorithm',
    'bellmanfordalgorithm': 'Bellman-Ford Algorithm',
    'better auth': 'Better Auth',
    'better-auth': 'Better Auth',
    'betterauth': 'Better Auth',
    'bigquery': 'BigQuery',
    'binary heaps': 'Binary Heaps',
    'binary search': 'Binary Search',
    'binary search trees': 'Binary Search Trees',
    'binary-heaps': 'Binary Heaps',
    'binary-search': 'Binary Search',
    'binary-search-trees': 'Binary Search Trees',
    'binaryheaps': 'Binary Heaps',
    'binarysearch': 'Binary Search',
    'binarysearchtrees': 'Binary Search Trees',
    'bit manipulation': 'Bit Manipulation',
    'bit-manipulation': 'Bit Manipulation',
    'bitbucket': 'Bitbucket',
    'bitcoin': 'Bitcoin',
    'bitmanipulation': 'Bit Manipulation',
    'blender': 'Blender',
    'blockchain': 'Blockchain',
    'bloom filters': 'Bloom Filters',
    'bloom-filters': 'Bloom Filters',
    'bloomfilters': 'Bloom Filters',
    'bootstrap': 'Bootstrap',
    'breadth first search': 'Breadth-First Search',
    'breadth-first search': 'Breadth-First Search',
    'breadth-first-search': 'Breadth-First Search',
    'breadthfirstsearch': 'Breadth-First Search',
    'brownie': 'Brownie',
    'btrees': 'B-Trees',
    'bullmq': 'BullMQ',
    'bun': 'Bun',
    'burp': 'Burp Suite',
    'burp suite': 'Burp Suite',
    'burp-suite': 'Burp Suite',
    'burpsuite': 'Burp Suite',
    'c': 'C',
    'c#': 'C#',
    'c++': 'C++',
    'caddy': 'Caddy',
    'cairo language': 'Cairo Language',
    'cairo-language': 'Cairo Language',
    'cairolanguage': 'Cairo Language',
    'canvas api': 'Canvas API',
    'canvas-api': 'Canvas API',
    'canvasapi': 'Canvas API',
    'cassandra': 'Cassandra',
    'celery': 'Celery',
    'centos': 'CentOS',
    'chainlink': 'Chainlink',
    'chromadb': 'ChromaDB',
    'ci/cd': 'CI/CD',
    'cicd': 'CI/CD',
    'circleci': 'CircleCI',
    'circuit breaker pattern': 'Circuit Breaker Pattern',
    'circuit-breaker-pattern': 'Circuit Breaker Pattern',
    'circuitbreakerpattern': 'Circuit Breaker Pattern',
    'clean architecture': 'Clean Architecture',
    'clean-architecture': 'Clean Architecture',
    'cleanarchitecture': 'Clean Architecture',
    'clerk': 'Clerk',
    'clerk authentication': 'Clerk Authentication',
    'clerk-authentication': 'Clerk Authentication',
    'clerkauthentication': 'Clerk Authentication',
    'clickhouse': 'ClickHouse',
    'clojure': 'Clojure',
    'cloud computing': 'Cloud Computing',
    'cloud-computing': 'Cloud Computing',
    'cloudcomputing': 'Cloud Computing',
    'cloudflare access': 'Cloudflare Access',
    'cloudflare d1': 'Cloudflare D1',
    'cloudflare edge': 'Cloudflare Edge',
    'cloudflare kv': 'Cloudflare KV',
    'cloudflare pages': 'Cloudflare Pages',
    'cloudflare queue': 'Cloudflare Queue',
    'cloudflare r2': 'Cloudflare R2',
    'cloudflare tunnel': 'Cloudflare Tunnel',
    'cloudflare turnstile': 'Cloudflare Turnstile',
    'cloudflare workers': 'Cloudflare Workers',
    'cloudflare zaraz': 'Cloudflare Zaraz',
    'cloudflare-access': 'Cloudflare Access',
    'cloudflare-d1': 'Cloudflare D1',
    'cloudflare-edge': 'Cloudflare Edge',
    'cloudflare-kv': 'Cloudflare KV',
    'cloudflare-pages': 'Cloudflare Pages',
    'cloudflare-queue': 'Cloudflare Queue',
    'cloudflare-r2': 'Cloudflare R2',
    'cloudflare-tunnel': 'Cloudflare Tunnel',
    'cloudflare-turnstile': 'Cloudflare Turnstile',
    'cloudflare-workers': 'Cloudflare Workers',
    'cloudflare-zaraz': 'Cloudflare Zaraz',
    'cloudflareaccess': 'Cloudflare Access',
    'cloudflared1': 'Cloudflare D1',
    'cloudflareedge': 'Cloudflare Edge',
    'cloudflarekv': 'Cloudflare KV',
    'cloudflarepages': 'Cloudflare Pages',
    'cloudflarequeue': 'Cloudflare Queue',
    'cloudflarer2': 'Cloudflare R2',
    'cloudflaretunnel': 'Cloudflare Tunnel',
    'cloudflareturnstile': 'Cloudflare Turnstile',
    'cloudflareworkers': 'Cloudflare Workers',
    'cloudflarezaraz': 'Cloudflare Zaraz',
    'cloudformation': 'CloudFormation',
    'cloudinary': 'Cloudinary',
    'cockroachdb': 'CockroachDB',
    'computer graphics': 'Computer Graphics',
    'computer networks': 'Computer Networks',
    'computer-graphics': 'Computer Graphics',
    'computer-networks': 'Computer Networks',
    'computergraphics': 'Computer Graphics',
    'computernetworks': 'Computer Networks',
    'concurrency': 'Concurrency',
    'contextapi': 'React Context',
    'context-api': 'React Context',
    'cosmos db': 'Cosmos DB',
    'cosmos sdk': 'Cosmos SDK',
    'cosmos-db': 'Cosmos DB',
    'cosmos-sdk': 'Cosmos SDK',
    'cosmosdb': 'Cosmos DB',
    'cosmossdk': 'Cosmos SDK',
    'cpu scheduling': 'CPU Scheduling',
    'cpu-scheduling': 'CPU Scheduling',
    'cpuscheduling': 'CPU Scheduling',
    'cqrs pattern': 'CQRS Pattern',
    'cqrs-pattern': 'CQRS Pattern',
    'cqrspattern': 'CQRS Pattern',
    'crewai agent': 'CrewAI Agent',
    'crewai-agent': 'CrewAI Agent',
    'crewaiagent': 'CrewAI Agent',
    'css': 'CSS',
    'dart': 'Dart',
    'data structures': 'Data Structures',
    'data-structures': 'Data Structures',
    'databricks': 'Databricks',
    'datadog': 'Datadog',
    'datastructures': 'Data Structures',
    'dbms': 'DBMS',
    'deadlocks': 'Deadlocks',
    'debian': 'Debian',
    'deno': 'Deno',
    'deno.js': 'Deno',
    'denojs': 'Deno',
    'depth first search': 'Depth-First Search',
    'depth-first search': 'Depth-First Search',
    'depth-first-search': 'Depth-First Search',
    'depthfirstsearch': 'Depth-First Search',
    'deques': 'Deques',
    'devops': 'DevOps',
    'dhcp': 'DHCP',
    'digitalocean solutions': 'DigitalOcean Solutions',
    'digitalocean-solutions': 'DigitalOcean Solutions',
    'digitaloceansolutions': 'DigitalOcean Solutions',
    'dijkstra\'s shortest path algorithm': 'Dijkstra\'s Shortest Path Algorithm',
    'dijkstra\'s-shortest-path-algorithm': 'Dijkstra\'s Shortest Path Algorithm',
    'dijkstrasshortestpathalgorithm': 'Dijkstra\'s Shortest Path Algorithm',
    'disjoint set union': 'Disjoint Set Union',
    'disjoint-set-union': 'Disjoint Set Union',
    'disjointsetunion': 'Disjoint Set Union',
    'distributed systems': 'Distributed Systems',
    'distributed-systems': 'Distributed Systems',
    'distributedsystems': 'Distributed Systems',
    'django': 'Django',
    'dns': 'DNS',
    'docker': 'Docker',
    'docker swarm': 'Docker Swarm',
    'docker-swarm': 'Docker Swarm',
    'dockerswarm': 'Docker Swarm',
    'domain driven design': 'Domain-Driven Design',
    'domain-driven design': 'Domain-Driven Design',
    'domain-driven-design': 'Domain-Driven Design',
    'domaindrivendesign': 'Domain-Driven Design',
    'dotnet': 'ASP.NET',
    'drizzle': 'Drizzle',
    'dynamic programming': 'Dynamic Programming',
    'dynamic-programming': 'Dynamic Programming',
    'dynamicprogramming': 'Dynamic Programming',
    'dynamodb': 'DynamoDB',
    'eclipse': 'Eclipse',
    'ecmascript': 'ECMAScript',
    'elasticsearch': 'Elasticsearch',
    'electron': 'Electron',
    'elixir': 'Elixir',
    'elk stack': 'ELK Stack',
    'elk-stack': 'ELK Stack',
    'elkstack': 'ELK Stack',
    'emacs': 'Emacs',
    'emotion': 'Emotion',
    'envoy': 'Envoy',
    'erlang': 'Erlang',
    'eslint': 'ESLint',
    'ethereum': 'Ethereum',
    'ethers': 'Ethers.js',
    'ethers.js': 'Ethers.js',
    'ethersjs': 'Ethers.js',
    'event driven architecture': 'Event-Driven Architecture',
    'event sourcing': 'Event Sourcing',
    'event-driven architecture': 'Event-Driven Architecture',
    'event-driven-architecture': 'Event-Driven Architecture',
    'event-sourcing': 'Event Sourcing',
    'eventdrivenarchitecture': 'Event-Driven Architecture',
    'eventsourcing': 'Event Sourcing',
    'expo': 'Expo',
    'express': 'Express.js',
    'express.js': 'Express.js',
    'expressjs': 'Express.js',
    'f': 'F#',
    'f#': 'F#',
    'fastapi': 'FastAPI',
    'fastify': 'Fastify',
    'fastly': 'Fastly',
    'fedora': 'Fedora',
    'fenwick trees': 'Fenwick Trees',
    'fenwick-trees': 'Fenwick Trees',
    'fenwicktrees': 'Fenwick Trees',
    'fiber': 'Fiber',
    'figma': 'Figma',
    'firebase': 'Firebase',
    'firebase cloud messaging': 'Firebase Cloud Messaging',
    'firebase realtime database': 'Firebase Realtime Database',
    'firebase-cloud-messaging': 'Firebase Cloud Messaging',
    'firebase-realtime-database': 'Firebase Realtime Database',
    'firebasecloudmessaging': 'Firebase Cloud Messaging',
    'firebaserealtimedatabase': 'Firebase Realtime Database',
    'firestore': 'Firestore',
    'flask': 'Flask',
    'flink': 'Flink',
    'floyd warshall algorithm': 'Floyd-Warshall Algorithm',
    'floyd-warshall algorithm': 'Floyd-Warshall Algorithm',
    'floyd-warshall-algorithm': 'Floyd-Warshall Algorithm',
    'floydwarshallalgorithm': 'Floyd-Warshall Algorithm',
    'flutter': 'Flutter',
    'flux': 'Flux',
    'foundry': 'Foundry',
    'framer motion': 'Framer Motion',
    'framer-motion': 'Framer Motion',
    'framermotion': 'Framer Motion',
    'ftp': 'FTP',
    'ganache': 'Ganache',
    'gcp': 'GCP',
    'gin': 'Gin',
    'git': 'Git',
    'github': 'GitHub',
    'github actions': 'GitHub Actions',
    'github copilot': 'GitHub Copilot',
    'github pages': 'GitHub Pages',
    'github-actions': 'GitHub Actions',
    'github-copilot': 'GitHub Copilot',
    'github-pages': 'GitHub Pages',
    'githubactions': 'GitHub Actions',
    'githubcopilot': 'GitHub Copilot',
    'githubpages': 'GitHub Pages',
    'gitlab': 'GitLab',
    'gnu make': 'Make',
    'go': 'Go',
    'google analytics': 'Google Analytics',
    'google bigquery': 'Google BigQuery',
    'google cloud': 'Google Cloud',
    'google cloud functions': 'Google Cloud Functions',
    'google cloud run': 'Google Cloud Run',
    'google cloud spanner': 'Google Cloud Spanner',
    'google cloud sql': 'Google Cloud SQL',
    'google cloud storage': 'Google Cloud Storage',
    'google compute engine': 'Google Compute Engine',
    'google identity platform': 'Google Identity Platform',
    'google kubernetes engine (gke)': 'Google Kubernetes Engine (GKE)',
    'google maps apis': 'Google Maps APIs',
    'google pub/sub': 'Google Pub/Sub',
    'google-analytics': 'Google Analytics',
    'google-bigquery': 'Google BigQuery',
    'google-cloud': 'Google Cloud',
    'google-cloud-functions': 'Google Cloud Functions',
    'google-cloud-run': 'Google Cloud Run',
    'google-cloud-spanner': 'Google Cloud Spanner',
    'google-cloud-sql': 'Google Cloud SQL',
    'google-cloud-storage': 'Google Cloud Storage',
    'google-compute-engine': 'Google Compute Engine',
    'google-identity-platform': 'Google Identity Platform',
    'google-kubernetes-engine-(gke)': 'Google Kubernetes Engine (GKE)',
    'google-maps-apis': 'Google Maps APIs',
    'google-pub/sub': 'Google Pub/Sub',
    'googleanalytics': 'Google Analytics',
    'googlebigquery': 'Google BigQuery',
    'googlecloud': 'Google Cloud',
    'googlecloudfunctions': 'Google Cloud Functions',
    'googlecloudrun': 'Google Cloud Run',
    'googlecloudspanner': 'Google Cloud Spanner',
    'googlecloudsql': 'Google Cloud SQL',
    'googlecloudstorage': 'Google Cloud Storage',
    'googlecomputeengine': 'Google Compute Engine',
    'googleidentityplatform': 'Google Identity Platform',
    'googlekubernetesenginegke': 'Google Kubernetes Engine (GKE)',
    'googlemapsapis': 'Google Maps APIs',
    'googlepubsub': 'Google Pub/Sub',
    'gradle': 'Gradle',
    'grafana': 'Grafana',
    'grafana k6': 'K6',
    'graphql': 'GraphQL',
    'greedy': 'Greedy',
    'groovy': 'Groovy',
    'grpc': 'gRPC',
    'hadoop': 'Hadoop',
    'haproxy': 'HAProxy',
    'hardhat development': 'Hardhat Development',
    'hardhat-development': 'Hardhat Development',
    'hardhatdevelopment': 'Hardhat Development',
    'hashicorp terraform': 'Terraform',
    'hashicorp vault': 'HashiCorp Vault',
    'hashicorp-vault': 'HashiCorp Vault',
    'hashicorpvault': 'HashiCorp Vault',
    'haskell': 'Haskell',
    'hbase': 'HBase',
    'headless ui': 'Headless UI',
    'headless-ui': 'Headless UI',
    'headlessui': 'Headless UI',
    'helm kubernetes': 'Helm Kubernetes',
    'helm-kubernetes': 'Helm Kubernetes',
    'helmkubernetes': 'Helm Kubernetes',
    'heroku': 'Heroku',
    'hexagonal architecture': 'Hexagonal Architecture',
    'hexagonal-architecture': 'Hexagonal Architecture',
    'hexagonalarchitecture': 'Hexagonal Architecture',
    'hibernate': 'Hibernate',
    'homebrew': 'Homebrew',
    'hono': 'Hono',
    'html': 'HTML',
    'http': 'HTTP',
    'http/1.1': 'HTTP/1.1',
    'http/2 protocols': 'HTTP/2 Protocols',
    'http/2-protocols': 'HTTP/2 Protocols',
    'http/3': 'HTTP/3',
    'http11': 'HTTP/1.1',
    'http2protocols': 'HTTP/2 Protocols',
    'http3': 'HTTP/3',
    'https': 'HTTPS',
    'hub spot': 'Hubspot',
    'hubspot': 'Hubspot',
    'hubspot crm': 'Hubspot',
    'hugging face': 'Hugging Face',
    'hugging-face': 'Hugging Face',
    'huggingface': 'Hugging Face',
    'husky': 'Husky',
    'iac': 'Infrastructure as Code',
    'indexeddb': 'IndexedDB',
    'influxdb': 'InfluxDB',
    'infra as code': 'Infrastructure as Code',
    'infra-as-code': 'Infrastructure as Code',
    'infrastructure as code': 'Infrastructure as Code',
    'infrastructure-as-code': 'Infrastructure as Code',
    'infrastructureascode': 'Infrastructure as Code',
    'intellij idea': 'IntelliJ IDEA',
    'intellij-idea': 'IntelliJ IDEA',
    'intellijidea': 'IntelliJ IDEA',
    'inter process communication': 'Inter-Process Communication',
    'inter-process communication': 'Inter-Process Communication',
    'inter-process-communication': 'Inter-Process Communication',
    'interprocesscommunication': 'Inter-Process Communication',
    'ios swiftui': 'iOS SwiftUI',
    'ios-swiftui': 'iOS SwiftUI',
    'iosswiftui': 'iOS SwiftUI',
    'ipfs': 'IPFS',
    'ipv4': 'IPv4',
    'ipv6 subnetting': 'IPv6 Subnetting',
    'ipv6-subnetting': 'IPv6 Subnetting',
    'ipv6subnetting': 'IPv6 Subnetting',
    'java': 'Java',
    'javascript': 'Javascript',
    'jenkins': 'Jenkins',
    'jest': 'Jest',
    'jetpack compose': 'Jetpack Compose',
    'jetpack-compose': 'Jetpack Compose',
    'jetpackcompose': 'Jetpack Compose',
    'jotai': 'Jotai',
    'jquery': 'jQuery',
    'julia': 'Julia',
    'jwt authentication': 'JWT Authentication',
    'jwt-authentication': 'JWT Authentication',
    'jwtauthentication': 'JWT Authentication',
    'k6': 'K6',
    'k6.io': 'K6',
    'kali': 'Kali Linux',
    'kali linux': 'Kali Linux',
    'kali-linux': 'Kali Linux',
    'kalilinux': 'Kali Linux',
    'keras api': 'Keras API',
    'keras-api': 'Keras API',
    'kerasapi': 'Keras API',
    'keydb': 'KeyDB',
    'kibana': 'Kibana',
    'kinde': 'Kinde',
    'knex': 'Knex.js',
    'knex.js': 'Knex.js',
    'knexjs': 'Knex.js',
    'kotlin': 'Kotlin',
    'kruskal\'s': 'Kruskal\'s',
    'kruskals': 'Kruskal\'s',
    'kubernetes': 'Kubernetes',
    'langchain': 'LangChain',
    'laravel': 'Laravel',
    'linked lists': 'Linked Lists',
    'linked-lists': 'Linked Lists',
    'linkedlists': 'Linked Lists',
    'linux': 'Linux',
    'linux server administration': 'Linux Server Administration',
    'linux-server-administration': 'Linux Server Administration',
    'linuxserveradministration': 'Linux Server Administration',
    'livekit webrtc': 'Livekit WebRTC',
    'livekit-webrtc': 'Livekit WebRTC',
    'livekitwebrtc': 'Livekit WebRTC',
    'llamaindex': 'LlamaIndex',
    'logstash': 'Logstash',
    'lora': 'LoRA',
    'lua': 'Lua',
    'lucia auth': 'Lucia Auth',
    'lucia-auth': 'Lucia Auth',
    'luciaauth': 'Lucia Auth',
    'machine coding': 'Machine Coding',
    'machine learning': 'Machine Learning',
    'machine-coding': 'Machine Coding',
    'machine-learning': 'Machine Learning',
    'machinecoding': 'Machine Coding',
    'machinelearning': 'Machine Learning',
    'macos': 'MacOS',
    'make': 'Make',
    'makefile': 'Make',
    'mapbox': 'Mapbox',
    'mariadb': 'MariaDB',
    'matplotlib': 'Matplotlib',
    'matrices': 'Matrices',
    'maven': 'Maven',
    'mean': 'Mean',
    'mean stack': 'Mean',
    'mean-stack': 'Mean',
    'meanstack': 'Mean',
    'memcached': 'Memcached',
    'merkle trees': 'Merkle Trees',
    'merkle-trees': 'Merkle Trees',
    'merkletrees': 'Merkle Trees',
    'mern': 'MERN',
    'mern stack': 'MERN',
    'mern-stack': 'MERN',
    'mernstack': 'MERN',
    'metabase': 'Metabase',
    'metamask': 'MetaMask',
    'micro frontends': 'Micro-Frontends',
    'micro-frontends': 'Micro-Frontends',
    'microfrontends': 'Micro-Frontends',
    'microservices architecture': 'Microservices Architecture',
    'microservices-architecture': 'Microservices Architecture',
    'microservicesarchitecture': 'Microservices Architecture',
    'microsoft azure': 'Microsoft Azure',
    'microsoft-azure': 'Microsoft Azure',
    'microsoftazure': 'Microsoft Azure',
    'milvus': 'Milvus',
    'mlflow': 'MLflow',
    'mobx': 'MobX',
    'mocha': 'Mocha',
    'mongodb': 'MongoDB',
    'mongoose': 'Mongoose',
    'monitoring': 'Monitoring',
    'monolithic architecture': 'Monolithic Architecture',
    'monolithic-architecture': 'Monolithic Architecture',
    'monolithicarchitecture': 'Monolithic Architecture',
    'monorepo': 'Monorepo',
    'monotonic stacks': 'Monotonic Stacks',
    'monotonic-stacks': 'Monotonic Stacks',
    'monotonicstacks': 'Monotonic Stacks',
    'moralis': 'Moralis',
    'move language': 'Move Language',
    'move-language': 'Move Language',
    'movelanguage': 'Move Language',
    'mqtt': 'MQTT',
    'mui': 'MUI',
    'multithreading': 'Multithreading',
    'mutexes, semaphores': 'Mutexes, Semaphores',
    'mutexes,-semaphores': 'Mutexes, Semaphores',
    'mutexessemaphores': 'Mutexes, Semaphores',
    'mysql': 'MySQL',
    'nat traversal': 'NAT Traversal',
    'nat-traversal': 'NAT Traversal',
    'nats': 'NATS',
    'nattraversal': 'NAT Traversal',
    'neo4j': 'Neo4j',
    'neon': 'Neon',
    'neovim': 'Neovim',
    'nest': 'NestJS',
    'nest.js': 'NestJS',
    'nestjs': 'NestJS',
    'netlify': 'Netlify',
    'netlify edge functions': 'Netlify Edge Functions',
    'netlify identity': 'Netlify Identity',
    'netlify-edge-functions': 'Netlify Edge Functions',
    'netlify-identity': 'Netlify Identity',
    'netlifyedgefunctions': 'Netlify Edge Functions',
    'netlifyidentity': 'Netlify Identity',
    'new relic': 'New Relic',
    'new-relic': 'New Relic',
    'newrelic': 'New Relic',
    'next': 'Next.js',
    'next.js': 'Next.js',
    'nextauth': 'NextAuth.js',
    'nextauth.js': 'NextAuth.js',
    'nextauthjs': 'NextAuth.js',
    'nextjs': 'Next.js',
    'nginx': 'Nginx',
    'nim': 'Nim',
    'nim lang': 'Nim',
    'nim language': 'Nim',
    'node': 'Node.js',
    'node.js': 'Node.js',
    'nodejs': 'Node.js',
    'npm': 'npm',
    'numpy': 'NumPy',
    'nuxt': 'Nuxt.js',
    'nuxt.js': 'Nuxt.js',
    'nuxtjs': 'Nuxt.js',
    'nx': 'Nx Monorepo',
    'nx monorepo': 'Nx Monorepo',
    'nx workspace': 'Nx Monorepo',
    'nx-monorepo': 'Nx Monorepo',
    'nx.dev': 'Nx Monorepo',
    'nxmonorepo': 'Nx Monorepo',
    'oauth 2.0': 'OAuth 2.0',
    'oauth-2.0': 'OAuth 2.0',
    'oauth20': 'OAuth 2.0',
    'object oriented programming': 'Object-Oriented Programming',
    'object-oriented programming': 'Object-Oriented Programming',
    'object-oriented-programming': 'Object-Oriented Programming',
    'objective c': 'Objective-C',
    'objective-c': 'Objective-C',
    'objectivec': 'Objective-C',
    'objectorientedprogramming': 'Object-Oriented Programming',
    'okta': 'Okta',
    'ollama local llm': 'Ollama Local LLM',
    'ollama-local-llm': 'Ollama Local LLM',
    'ollamalocalllm': 'Ollama Local LLM',
    'onnx': 'ONNX',
    'oop': 'OOP',
    'openai api': 'OpenAI API ',
    'openai-api-': 'OpenAI API ',
    'openaiapi': 'OpenAI API ',
    'opencv': 'OpenCV',
    'openid connect': 'OpenID Connect',
    'openid-connect': 'OpenID Connect',
    'openidconnect': 'OpenID Connect',
    'opensearch': 'OpenSearch',
    'opentelemetry': 'OpenTelemetry',
    'opentofu iac': 'OpenTofu IaC',
    'opentofu-iac': 'OpenTofu IaC',
    'opentofuiac': 'OpenTofu IaC',
    'operating systems': 'Operating Systems',
    'operating-systems': 'Operating Systems',
    'operatingsystems': 'Operating Systems',
    'optimism': 'Optimism',
    'oracle': 'Oracle',
    'page replacement algorithms': 'Page Replacement Algorithms',
    'page-replacement-algorithms': 'Page Replacement Algorithms',
    'pagereplacementalgorithms': 'Page Replacement Algorithms',
    'paging': 'Paging',
    'pandas': 'Pandas',
    'parllelism': 'Parallelism',
    'perl': 'Perl',
    'pern': "PERN",
    'pern stack': "PERN",
    'pern-stack': "PERN",
    'pernstack': "PERN",
    'php': 'PHP',
    'pinecone': 'Pinecone',
    'pip': 'pip',
    'planetscale': 'PlanetScale',
    'playwright': 'Playwright',
    'plotly': 'Plotly',
    'pnpm': 'pnpm',
    'podman': 'Podman',
    'polkadot': 'Polkadot',
    'polygon': 'Polygon',
    'postcss': 'PostCSS',
    'postgresql': 'PostgreSQL',
    'postman': 'Postman',
    'powershell': 'PowerShell',
    'prettier': 'Prettier',
    'prim\'s mst algorithms': 'Prim\'s MST Algorithms',
    'prim\'s-mst-algorithms': 'Prim\'s MST Algorithms',
    'primsmstalgorithms': 'Prim\'s MST Algorithms',
    'priority queues': 'Priority Queues',
    'priority-queues': 'Priority Queues',
    'priorityqueues': 'Priority Queues',
    'prisma': 'Prisma',
    'prometheus': 'Prometheus',
    'protocol buffers': 'Protocol Buffers',
    'protocol-buffers': 'Protocol Buffers',
    'protocolbuffers': 'Protocol Buffers',
    'pruning': 'Pruning',
    'pub/sub': 'Pub/Sub',
    'pubsub': 'Pub/Sub',
    'pulumi': 'Pulumi',
    'pydantic': 'Pydantic',
    'python': 'Python',
    'pytorch': 'PyTorch',
    'qdrant': 'Qdrant',
    'qlora fine tuning': 'QLoRA Fine-Tuning',
    'qlora fine-tuning': 'QLoRA Fine-Tuning',
    'qlora-fine-tuning': 'QLoRA Fine-Tuning',
    'qlorafinetuning': 'QLoRA Fine-Tuning',
    'quadtrees & r trees': 'Quadtrees & R-Trees',
    'quadtrees & r-trees': 'Quadtrees & R-Trees',
    'quadtrees and r-trees': 'Quadtrees & R-Trees',
    'quadtrees r-trees': 'Quadtrees & R-Trees',
    'quadtrees-&-r-trees': 'Quadtrees & R-Trees',
    'quadtreesrtrees': 'Quadtrees & R-Trees',
    'queues': 'Queues',
    'quic protocol': 'QUIC Protocol',
    'quic-protocol': 'QUIC Protocol',
    'quicknode': 'QuickNode',
    'quicprotocol': 'QUIC Protocol',
    'r': 'R',
    'rabbitmq': 'RabbitMQ',
    'radix ui': 'Radix UI',
    'radix-ui': 'Radix UI',
    'radixui': 'Radix UI',
    'railway': 'Railway',
    'razorpay': 'Razorpay',
    'react': 'React.js',
    'react-context': 'React Context',
    'react context': 'React Context',
    'react context api': 'React Context',
    'reactcontext': 'React Context',
    'react hook form': 'React Hook Form',
    'react native': 'React Native',
    'react router': 'React Router',
    'react three fiber': 'React Three Fiber',
    'react-hook-form': 'React Hook Form',
    'react-native': 'React Native',
    'react-router': 'React Router',
    'react-three-fiber': 'React Three Fiber',
    'react.js': 'React.js',
    'reacthookform': 'React Hook Form',
    'reactjs': 'React.js',
    'reactnative': 'React Native',
    'reactrouter': 'React Router',
    'reactthreefiber': 'React Three Fiber',
    'recoil': 'Recoil',
    'red black trees': 'Red-Black Trees',
    'red-black trees': 'Red-Black Trees',
    'red-black-trees': 'Red-Black Trees',
    'redblacktrees': 'Red-Black Trees',
    'redis': 'Redis',
    'redshift': 'Redshift',
    'redux saga': 'Redux Saga',
    'redux thunk': 'Redux Thunk',
    'redux toolkit': 'Redux Toolkit',
    'redux-saga': 'Redux Saga',
    'redux-thunk': 'Redux Thunk',
    'redux-toolkit': 'Redux Toolkit',
    'reduxsaga': 'Redux Saga',
    'reduxthunk': 'Redux Thunk',
    'reduxtoolkit': 'Redux Toolkit',
    'relay': 'Relay',
    'render': 'Render',
    'resend': 'Resend',
    'restful api': 'RESTful API',
    'restful-api': 'RESTful API',
    'restfulapi': 'RESTful API',
    'reverse proxy': 'Reverse Proxy',
    'reverse-proxy': 'Reverse Proxy',
    'reverseproxy': 'Reverse Proxy',
    'rtk query': 'RTK Query',
    'rtk-query': 'RTK Query',
    'rtkquery': 'RTK Query',
    'ruby on rails': 'Ruby on Rails',
    'ruby-on-rails': 'Ruby on Rails',
    'rubyonrails': 'Ruby on Rails',
    'rust': 'Rust',
    'saga pattern': 'Saga Pattern',
    'saga-pattern': 'Saga Pattern',
    'sagapattern': 'Saga Pattern',
    'sales force': 'Salesforce',
    'salesforce': 'Salesforce',
    'scala': 'Scala',
    'scikit learn': 'Scikit-Learn',
    'scikit-learn': 'Scikit-Learn',
    'scikitlearn': 'Scikit-Learn',
    'scipy': 'SciPy',
    'scss': 'SCSS',
    'scylladb': 'ScyllaDB',
    'seaborn': 'Seaborn',
    'segment trees': 'Segment Trees',
    'segment-trees': 'Segment Trees',
    'segmenttrees': 'Segment Trees',
    'selenium': 'Selenium',
    'sendgrid': 'SendGrid',
    'sentry': 'Sentry',
    'sequelize': 'Sequelize',
    'serverless': 'Serverless',
    'serverless architecture': 'Serverless Architecture',
    'serverless-architecture': 'Serverless Architecture',
    'serverlessarchitecture': 'Serverless Architecture',
    'service mesh': 'Service Mesh',
    'service workers': 'Service Workers',
    'service-mesh': 'Service Mesh',
    'service-workers': 'Service Workers',
    'servicemesh': 'Service Mesh',
    'serviceworkers': 'Service Workers',
    'sfdc': 'Salesforce',
    'shad cn': 'Shad CN',
    'shad-cn': 'Shad CN',
    'shadcn': 'Shad CN',
    'skip lists': 'Skip Lists',
    'skip-lists': 'Skip Lists',
    'skiplists': 'Skip Lists',
    'sliding window': 'Sliding Window',
    'sliding-window': 'Sliding Window',
    'slidingwindow': 'Sliding Window',
    'smtp': 'SMTP',
    'snowflake data warehouse': 'Snowflake Data Warehouse',
    'snowflake-data-warehouse': 'Snowflake Data Warehouse',
    'snowflakedatawarehouse': 'Snowflake Data Warehouse',
    'socket.io': 'Socket.io',
    'socketio': 'Socket.io',
    'solana blockchain': 'Solana Blockchain',
    'solana-blockchain': 'Solana Blockchain',
    'solanablockchain': 'Solana Blockchain',
    'solidity': 'Solidity',
    'spacy & nltk': 'spaCy & NLTK',
    'spacy and nltk': 'spaCy & NLTK',
    'spacy nltk': 'spaCy & NLTK',
    'spacy-&-nltk': 'spaCy & NLTK',
    'spacynltk': 'spaCy & NLTK',
    'spark': 'Spark',
    'splay trees': 'Splay Trees',
    'splay-trees': 'Splay Trees',
    'splaytrees': 'Splay Trees',
    'spline': 'Spline',
    'spring': 'Spring',
    'spring boot': 'Spring Boot',
    'spring security': 'Spring Security',
    'spring-boot': 'Spring Boot',
    'spring-security': 'Spring Security',
    'springboot': 'Spring Boot',
    'springsecurity': 'Spring Security',
    'sql server': 'SQL Server',
    'sql-server': 'SQL Server',
    'sqlite': 'SQLite',
    'sqlserver': 'SQL Server',
    'ssh': 'SSH',
    'stacks': 'Stacks',
    'starknet': 'StarkNet',
    'storybook': 'Storybook',
    'strangler fig pattern': 'Strangler Fig Pattern',
    'strangler-fig-pattern': 'Strangler Fig Pattern',
    'stranglerfigpattern': 'Strangler Fig Pattern',
    'strapi': 'Strapi',
    'streamlit & gradio': 'Streamlit & Gradio',
    'streamlit and gradio': 'Streamlit & Gradio',
    'streamlit gradio': 'Streamlit & Gradio',
    'streamlit-&-gradio': 'Streamlit & Gradio',
    'streamlitgradio': 'Streamlit & Gradio',
    'stripe': 'Stripe',
    'styled components': 'Styled Components',
    'styled-components': 'Styled Components',
    'styledcomponents': 'Styled Components',
    'substrate': 'Substrate',
    'supabase': 'Supabase',
    'supabase auth': 'Supabase Auth',
    'supabase-auth': 'Supabase Auth',
    'supabaseauth': 'Supabase Auth',
    'svelte': 'Svelte',
    'sveltekit': 'SvelteKit',
    'swift': 'Swift',
    'swr': 'SWR',
    'system design': 'System Design',
    'system-design': 'System Design',
    'systemdesign': 'System Design',
    'tableau': 'Tableau',
    'tailwind css': 'Tailwind CSS',
    'tailwind-css': 'Tailwind CSS',
    'tailwindcss': 'Tailwind CSS',
    'tanstack form': 'TanStack Form',
    'tanstack query': 'TanStack Query',
    'tanstack router': 'Tanstack Router',
    'tanstack table': 'TanStack Table',
    'tanstack virtual': 'TanStack Virtual',
    'tanstack-form': 'TanStack Form',
    'tanstack-query': 'TanStack Query',
    'tanstack-router': 'Tanstack Router',
    'tanstack-table': 'TanStack Table',
    'tanstack-virtual': 'TanStack Virtual',
    'tanstackform': 'TanStack Form',
    'tanstackquery': 'TanStack Query',
    'tanstackrouter': 'Tanstack Router',
    'tanstacktable': 'TanStack Table',
    'tanstackvirtual': 'TanStack Virtual',
    'tarjan\'s algorithm': 'Tarjan\'s Algorithm',
    'tarjan\'s-algorithm': 'Tarjan\'s Algorithm',
    'tarjansalgorithm': 'Tarjan\'s Algorithm',
    'tauri': 'Tauri',
    'tendermint': 'Tendermint',
    'tensorflow': 'TensorFlow',
    'tensorrt': 'TensorRT',
    'terraform': 'Terraform',
    'the graph & subgraphs': 'The Graph & Subgraphs',
    'the graph and subgraphs': 'The Graph & Subgraphs',
    'the graph subgraphs': 'The Graph & Subgraphs',
    'the-graph-&-subgraphs': 'The Graph & Subgraphs',
    'thegraphsubgraphs': 'The Graph & Subgraphs',
    'threads': 'Threads',
    'three': 'Three.js',
    'three.js': 'Three.js',
    'threejs': 'Three.js',
    'tls/ssl encryption': 'TLS/SSL Encryption',
    'tls/ssl-encryption': 'TLS/SSL Encryption',
    'tlssslencryption': 'TLS/SSL Encryption',
    'topological sorting': 'Topological Sorting',
    'topological-sorting': 'Topological Sorting',
    'topologicalsorting': 'Topological Sorting',
    'traefik': 'Traefik',
    'tries': 'Tries',
    'trpc': 'tRPC',
    'truffle': 'Truffle',
    'turbopack': 'Turbopack',
    'turborepo': 'Turborepo',
    'turn/stun servers': 'TURN/STUN Servers',
    'turn/stun-servers': 'TURN/STUN Servers',
    'turnstunservers': 'TURN/STUN Servers',
    'twilio': 'Twilio',
    'two pointers': 'Two Pointers',
    'two-pointers': 'Two Pointers',
    'twopointers': 'Two Pointers',
    'typegoose': 'Typegoose',
    'typeorm': 'TypeORM',
    'typescript': 'TypeScript',
    'typesense': 'Typesense',
    'ubuntu': 'Ubuntu',
    'udp': 'UDP',
    'ue': 'Unreal Engine',
    'ue4': 'Unreal Engine',
    'ue5': 'Unreal Engine',
    'unity': 'Unity',
    'unity 3d': 'Unity',
    'unity game engine': 'Unity',
    'unity3d': 'Unity',
    'unix': 'Unix',
    'unix shell scripting': 'Unix Shell Scripting',
    'unix-shell-scripting': 'Unix Shell Scripting',
    'unixshellscripting': 'Unix Shell Scripting',
    'unreal': 'Unreal Engine',
    'unreal engine': 'Unreal Engine',
    'unreal-engine': 'Unreal Engine',
    'unrealengine': 'Unreal Engine',
    'upstash': 'Upstash',
    'v8 engine': 'V8 Engine',
    'v8-engine': 'V8 Engine',
    'v8engine': 'V8 Engine',
    'vercel blob': 'Vercel Blob',
    'vercel deployment': 'Vercel Deployment',
    'vercel edge functions': 'Vercel Edge Functions',
    'vercel kv': 'Vercel KV',
    'vercel postgres': 'Vercel Postgres',
    'vercel-blob': 'Vercel Blob',
    'vercel-deployment': 'Vercel Deployment',
    'vercel-edge-functions': 'Vercel Edge Functions',
    'vercel-kv': 'Vercel KV',
    'vercel-postgres': 'Vercel Postgres',
    'vercelblob': 'Vercel Blob',
    'verceldeployment': 'Vercel Deployment',
    'verceledgefunctions': 'Vercel Edge Functions',
    'vercelkv': 'Vercel KV',
    'vercelpostgres': 'Vercel Postgres',
    'viem': 'Viem',
    'vim': 'Vim',
    'virtual memory': 'Virtual Memory',
    'virtual reality': 'Virtual Reality',
    'virtual-memory': 'Virtual Memory',
    'virtual-reality': 'Virtual Reality',
    'virtualmemory': 'Virtual Memory',
    'virtualreality': 'Virtual Reality',
    'vite': 'Vite',
    'vitest': 'Vitest',
    'vs code': 'VS Code',
    'vs-code': 'VS Code',
    'vscode': 'VS Code',
    'vue': 'Vue.js',
    'vue.js': 'Vue.js',
    'vuejs': 'Vue.js',
    'vyper': 'Vyper',
    'wagmi libraries': 'Wagmi Libraries',
    'wagmi-libraries': 'Wagmi Libraries',
    'wagmilibraries': 'Wagmi Libraries',
    'walletconnect': 'WalletConnect',
    'web accessibility': 'Web Accessibility',
    'web audio api': 'Web Audio API',
    'web workers': 'Web Workers',
    'web-accessibility': 'Web Accessibility',
    'web-audio-api': 'Web Audio API',
    'web-workers': 'Web Workers',
    'web3': 'Web3.js',
    'web3.js': 'Web3.js',
    'web3js': 'Web3.js',
    'webaccessibility': 'Web Accessibility',
    'webassembly': 'WebAssembly',
    'webaudioapi': 'Web Audio API',
    'webgl': 'WebGL',
    'webpack': 'Webpack',
    'webrtc': 'WebRTC',
    'websockets': 'WebSockets',
    'webworkers': 'Web Workers',
    'windows': 'Windows',
    'wireshark': 'Wireshark',
    'yarn': 'Yarn',
    'yolo & ssd': 'YOLO & SSD',
    'yolo and ssd': 'YOLO & SSD',
    'yolo ssd': 'YOLO & SSD',
    'yolo-&-ssd': 'YOLO & SSD',
    'yolossd': 'YOLO & SSD',
    'yup': 'Yup',
    'zeromq': 'ZeroMQ',
    'zksync': 'zkSync',
    'zod': 'ZOD',
    'zoho': 'Zoho',
    'zoho crm': 'Zoho',
    'zustand': 'Zustand'
};
