// Auto-generated skill importance scores mapping (0-100)
export const SKILL_IMPORTANCE: Record<string, number> = {
    'ActiveMQ': 50,
    'Actix Web': 50,
    'Adobe XD': 50,
    'Alchemy, Infura': 50,
    'Algolia & Meilisearch': 95,
    'Algorithms': 95,
    'AMQP': 50,
    'Anchor': 50,
    'Android SDK': 50,
    'Angular': 85,
    'Ansible': 50,
    'Ant Design': 50,
    'Anthropic Claude': 50,
    'Apache Airflow': 50,
    'Apache Cassandra': 50,
    'Apache Hadoop': 85,
    'Apache HTTP Server': 50,
    'Apache Kafka': 85,
    'Apache Pulsar': 50,
    'Apache Spark': 50,
    'API Gateway Pattern': 85,
    'Apollo Client': 50,
    'Apollo Server': 50,
    'Apple Push Notification Service': 50,
    'Appwrite': 50,
    'Arbitrum': 50,
    'Arch Linux': 75,
    'ArgoCD': 95,
    'Arrays': 50,
    'Artificial Intelligence': 50,
    'ASP.NET': 50,
    'Assembly': 50,
    'Athena': 50,
    'Augmented Reality': 50,
    'Auth0': 50,
    'AVL': 50,
    'AWS': 95,
    'AWS Batch': 95,
    'AWS CloudFormation': 95,
    'AWS CloudFront CDN': 95,
    'AWS CloudWatch': 95,
    'AWS Cognito': 95,
    'AWS DynamoDB': 95,
    'AWS EC2': 95,
    'AWS ECS': 95,
    'AWS EKS': 95,
    'AWS Elastic Beanstalk': 95,
    'AWS ElastiCache': 95,
    'AWS EventBridge': 95,
    'AWS IAM': 95,
    'AWS Kinesis Data Streams': 95,
    'AWS Lambda': 95,
    'AWS RDS': 95,
    'AWS Route 53': 95,
    'AWS Route 53 DNS': 95,
    'AWS S3': 95,
    'AWS Secrets Manager': 95,
    'AWS SNS': 95,
    'AWS SQS': 95,
    'AWS Step Functions': 95,
    'AWS VPC': 95,
    'Axum': 50,
    'Azure Active Directory': 85,
    'Azure App Service': 85,
    'Azure Blob Storage': 85,
    'Azure Cosmos DB': 85,
    'Azure DevOps': 85,
    'Azure Event Grid': 85,
    'Azure Functions': 85,
    'Azure Kubernetes Service (AKS)': 95,
    'Azure Service Bus': 85,
    'Azure SQL Database': 85,
    'B-Trees': 50,
    'Babel': 60,
    'Backend for Frontend': 85,
    'Backend-Driven Frontend': 50,
    'Backtracking': 50,
    'Bash': 75,
    'Bazel': 50,
    'Bellman-Ford Algorithm': 95,
    'Better Auth': 50,
    'BigQuery': 50,
    'Binary Heaps': 50,
    'Binary Search': 50,
    'Binary Search Trees': 50,
    'Bit Manipulation': 50,
    'Bitbucket': 50,
    'Bitcoin': 50,
    'Blender': 50,
    'Blockchain': 45,
    'Bloom Filters': 50,
    'Bootstrap': 60,
    'Breadth-First Search': 50,
    'Brownie': 50,
    'BullMQ': 50,
    'Bun': 50,
    'Burp Suite': 50,
    'C': 50,
    'C#': 85,
    'C++': 95,
    'Caddy': 50,
    'Cairo Language': 50,
    'Canvas API': 50,
    'Cassandra': 50,
    'Celery': 50,
    'CentOS': 50,
    'Chainlink': 50,
    'ChromaDB': 78,
    'CI/CD': 95,
    'CircleCI': 50,
    'Circuit Breaker Pattern': 82,
    'Clean Architecture': 82,
    'Clerk': 50,
    'Clerk Authentication': 50,
    'ClickHouse': 50,
    'Clojure': 50,
    'Cloud Computing': 82,
    'Cloudflare Access': 82,
    'Cloudflare D1': 82,
    'Cloudflare Edge': 82,
    'Cloudflare KV': 82,
    'Cloudflare Pages': 82,
    'Cloudflare Queue': 82,
    'Cloudflare R2': 82,
    'Cloudflare Tunnel': 82,
    'Cloudflare Turnstile': 82,
    'Cloudflare Workers': 82,
    'Cloudflare Zaraz': 82,
    'CloudFormation': 82,
    'Cloudinary': 82,
    'CockroachDB': 78,
    'Computer Graphics': 50,
    'Computer Networks': 50,
    'Concurrency': 50,
    'Cosmos DB': 78,
    'Cosmos SDK': 50,
    'CPU Scheduling': 50,
    'CQRS Pattern': 85,
    'CrewAI Agent': 50,
    'CSS': 75,
    'Dart': 50,
    'Data Structures': 95,
    'Databricks': 50,
    'Datadog': 50,
    'DBMS': 78,
    'Deadlocks': 50,
    'Debian': 50,
    'Deno': 50,
    'Depth-First Search': 50,
    'Deques': 50,
    'DevOps': 50,
    'DHCP': 50,
    'DigitalOcean Solutions': 75,
    'Dijkstra\'s Shortest Path Algorithm': 50,
    'Disjoint Set Union': 50,
    'Distributed Systems': 95,
    'Django': 95,
    'DNS': 50,
    'Docker': 95,
    'Docker Swarm': 95,
    'Domain-Driven Design': 95,
    'Drizzle': 50,
    'Dynamic Programming': 50,
    'DynamoDB': 78,
    'Eclipse': 50,
    'ECMAScript': 50,
    'Elasticsearch': 85,
    'Electron': 50,
    'Elixir': 50,
    'ELK Stack': 50,
    'Emacs': 50,
    'Emotion': 50,
    'Envoy': 50,
    'Erlang': 50,
    'ESLint': 50,
    'Ethereum': 50,
    'Ethers.js': 70,
    'Event Sourcing': 50,
    'Event-Driven Architecture': 95,
    'Expo': 50,
    'Express.js': 85,
    'F#': 50,
    'FastAPI': 50,
    'Fastify': 50,
    'Fastly': 50,
    'Fedora': 50,
    'Fenwick Trees': 50,
    'Fiber': 50,
    'Figma': 60,
    'Firebase': 50,
    'Firebase Cloud Messaging': 82,
    'Firebase Realtime Database': 78,
    'Firestore': 50,
    'Flask': 75,
    'Flink': 50,
    'Floyd-Warshall Algorithm': 95,
    'Flutter': 85,
    'Flux': 50,
    'Foundry': 50,
    'Framer Motion': 50,
    'FTP': 50,
    'Ganache': 50,
    'GCP': 85,
    'Gin': 50,
    'Git': 75,
    'GitHub': 75,
    'GitHub Actions': 75,
    'GitHub Copilot': 75,
    'GitHub Pages': 75,
    'GitLab': 75,
    'Go': 95,
    'Google Analytics': 50,
    'Google BigQuery': 95,
    'Google Cloud': 95,
    'Google Cloud Functions': 95,
    'Google Cloud Run': 95,
    'Google Cloud Spanner': 95,
    'Google Cloud SQL': 95,
    'Google Cloud Storage': 95,
    'Google Compute Engine': 95,
    'Google Identity Platform': 95,
    'Google Kubernetes Engine (GKE)': 95,
    'Google Maps APIs': 95,
    'Google Pub/Sub': 95,
    'Gradle': 50,
    'Grafana': 50,
    'GraphQL': 85,
    'Greedy': 50,
    'Groovy': 50,
    'gRPC': 50,
    'Hadoop': 85,
    'HAProxy': 50,
    'Hardhat Development': 50,
    'HashiCorp Vault': 50,
    'Haskell': 50,
    'HBase': 50,
    'Headless UI': 60,
    'Helm Kubernetes': 95,
    'Heroku': 50,
    'Hexagonal Architecture': 95,
    'Hibernate': 50,
    'Homebrew': 50,
    'Hono': 50,
    'HTML': 75,
    'HTTP': 50,
    'HTTP/1.1': 50,
    'HTTP/2 Protocols': 50,
    'HTTP/3': 50,
    'HTTPS': 50,
    'Hubspot': 50,
    'Hugging Face': 50,
    'Husky': 50,
    'IndexedDB': 78,
    'InfluxDB': 78,
    'Infrastructure as Code': 50,
    'IntelliJ IDEA': 50,
    'Inter-Process Communication': 50,
    'iOS SwiftUI': 75,
    'IPFS': 50,
    'IPv4': 50,
    'IPv6 Subnetting': 50,
    'Java': 95,
    'Javascript': 85,
    'Jenkins': 50,
    'Jest': 75,
    'Jetpack Compose': 50,
    'Jotai': 50,
    'jQuery': 60,
    'Julia': 50,
    'JWT Authentication': 50,
    'K6': 50,
    'Kali Linux': 75,
    'Keras API': 50,
    'KeyDB': 78,
    'Kibana': 50,
    'Kinde': 50,
    'Knex.js': 70,
    'Kotlin': 75,
    'Kruskal\'s': 50,
    'Kubernetes': 95,
    'LangChain': 50,
    'Laravel': 75,
    'Linked Lists': 50,
    'Linux': 75,
    'Linux Server Administration': 75,
    'Livekit WebRTC': 50,
    'LlamaIndex': 50,
    'Logstash': 50,
    'LoRA': 50,
    'Lua': 50,
    'Lucia Auth': 50,
    'Machine Coding': 50,
    'Machine Learning': 95,
    'MacOS': 50,
    'Make': 50,
    'Mapbox': 50,
    'MariaDB': 78,
    'Matplotlib': 50,
    'Matrices': 50,
    'Maven': 50,
    'MEAN': 70,
    'Memcached': 50,
    'Merkle Trees': 50,
    'MERN': 80,
    'Metabase': 50,
    'MetaMask': 50,
    'Micro-Frontends': 50,
    'Microservices Architecture': 95,
    'Microsoft Azure': 85,
    'Milvus': 50,
    'MLflow': 50,
    'MobX': 60,
    'Mocha': 50,
    'MongoDB': 95,
    'Mongoose': 95,
    'Monitoring': 50,
    'Monolithic Architecture': 82,
    'Monorepo': 50,
    'Monotonic Stacks': 50,
    'Moralis': 50,
    'Move Language': 50,
    'MQTT': 50,
    'MUI': 50,
    'Multithreading': 50,
    'Mutexes, Semaphores': 50,
    'MySQL': 85,
    'NAT Traversal': 50,
    'NATS': 50,
    'Neo4j': 50,
    'Neon': 50,
    'Neovim': 50,
    'NestJS': 70,
    'Netlify': 50,
    'Netlify Edge Functions': 50,
    'Netlify Identity': 50,
    'New Relic': 50,
    'Next.js': 95,
    'NextAuth.js': 70,
    'Nginx': 50,
    'Nim': 50,
    'Node.js': 95,
    'npm': 50,
    'NumPy': 50,
    'Nuxt.js': 70,
    'Nx Monorepo': 50,
    'OAuth 2.0': 50,
    'Object-Oriented Programming': 85,
    'Objective-C': 50,
    'Okta': 50,
    'Ollama Local LLM': 50,
    'ONNX': 50,
    'OOP': 85,
    'OpenAI API ': 50,
    'OpenCV': 50,
    'OpenID Connect': 50,
    'OpenSearch': 50,
    'OpenTelemetry': 50,
    'OpenTofu IaC': 50,
    'Operating Systems': 82,
    'Optimism': 50,
    'Oracle': 75,
    'Page Replacement Algorithms': 95,
    'Paging': 50,
    'Pandas': 50,
    'parallelism': 50,
    'Perl': 50,
    'PERN': 80,
    'PHP': 75,
    'Pinecone': 50,
    'pip': 50,
    'PlanetScale': 50,
    'Playwright': 60,
    'Plotly': 50,
    'pnpm': 50,
    'Podman': 50,
    'Polkadot': 50,
    'Polygon': 95,
    'PostCSS': 75,
    'PostgreSQL': 95,
    'Postman': 50,
    'PowerShell': 50,
    'Prettier': 50,
    'Prim\'s MST Algorithms': 50,
    'Priority Queues': 50,
    'Prisma': 50,
    'Prometheus': 50,
    'Protocol Buffers': 50,
    'Pruning': 50,
    'Pub/Sub': 50,
    'Pulumi': 50,
    'Pydantic': 50,
    'Python': 95,
    'PyTorch': 50,
    'Qdrant': 50,
    'QLoRA Fine-Tuning': 50,
    'Quadtrees & R-Trees': 50,
    'Queues': 50,
    'QUIC Protocol': 50,
    'QuickNode': 50,
    'R': 50,
    'RabbitMQ': 50,
    'Radix UI': 50,
    'Railway': 50,
    'Razorpay': 50,
    'React Context': 85,
    'React Hook Form': 95,
    'React Native': 95,
    'React Router': 95,
    'React Three Fiber': 95,
    'React.js': 95,
    'Recoil': 60,
    'Red-Black Trees': 50,
    'Redis': 85,
    'Redshift': 50,
    'Redux Saga': 50,
    'Redux Thunk': 50,
    'Redux Toolkit': 50,
    'Relay': 50,
    'Render': 50,
    'Resend': 50,
    'RESTful API': 50,
    'Reverse Proxy': 50,
    'RTK Query': 50,
    'Ruby on Rails': 75,
    'Rust': 85,
    'Saga Pattern': 85,
    'Salesforce': 50,
    'Scala': 50,
    'Scikit-Learn': 50,
    'SciPy': 50,
    'SCSS': 75,
    'ScyllaDB': 78,
    'Seaborn': 50,
    'Segment Trees': 50,
    'Selenium': 50,
    'SendGrid': 50,
    'Sentry': 50,
    'Sequelize': 50,
    'Serverless': 60,
    'Serverless Architecture': 60,
    'Service Mesh': 50,
    'Service Workers': 50,
    'Shad CN': 50,
    'Skip Lists': 50,
    'Sliding Window': 50,
    'SMTP': 50,
    'Snowflake Data Warehouse': 50,
    'Socket.io': 50,
    'Solana Blockchain': 50,
    'Solidity': 50,
    'spaCy & NLTK': 50,
    'Spark': 50,
    'Splay Trees': 50,
    'Spline': 50,
    'Spring': 50,
    'Spring Boot': 85,
    'Spring Security': 50,
    'SQL Server': 85,
    'SQLite': 85,
    'SSH': 50,
    'Stacks': 50,
    'StarkNet': 50,
    'Storybook': 50,
    'Strangler Fig Pattern': 82,
    'Strapi': 50,
    'Streamlit & Gradio': 50,
    'Stripe': 50,
    'Styled Components': 50,
    'Substrate': 50,
    'Supabase': 50,
    'Supabase Auth': 50,
    'Svelte': 50,
    'SvelteKit': 50,
    'Swift': 75,
    'SWR': 50,
    'System Design': 95,
    'Tableau': 50,
    'Tailwind CSS': 75,
    'TanStack Form': 50,
    'TanStack Query': 50,
    'Tanstack Router': 50,
    'TanStack Table': 50,
    'TanStack Virtual': 50,
    'Tarjan\'s Algorithm': 50,
    'Tauri': 50,
    'Tendermint': 50,
    'TensorFlow': 50,
    'TensorRT': 50,
    'Terraform': 85,
    'The Graph & Subgraphs': 50,
    'Threads': 50,
    'Three.js': 70,
    'TLS/SSL Encryption': 50,
    'Topological Sorting': 50,
    'Traefik': 50,
    'Tries': 50,
    'tRPC': 50,
    'Truffle': 50,
    'Turbopack': 50,
    'Turborepo': 50,
    'TURN/STUN Servers': 50,
    'Twilio': 50,
    'Two Pointers': 50,
    'Typegoose': 95,
    'TypeORM': 50,
    'TypeScript': 95,
    'Typesense': 50,
    'Ubuntu': 50,
    'UDP': 50,
    'Unity': 50,
    'Unix': 75,
    'Unix Shell Scripting': 75,
    'Unreal Engine': 50,
    'Upstash': 50,
    'V8 Engine': 50,
    'Vercel Blob': 50,
    'Vercel Deployment': 50,
    'Vercel Edge Functions': 50,
    'Vercel KV': 50,
    'Vercel Postgres': 50,
    'Viem': 50,
    'Vim': 50,
    'Virtual Memory': 50,
    'Virtual Reality': 50,
    'Vite': 60,
    'Vitest': 60,
    'VS Code': 50,
    'Vue.js': 85,
    'Vyper': 50,
    'Wagmi Libraries': 50,
    'WalletConnect': 50,
    'Web Accessibility': 50,
    'Web Audio API': 50,
    'Web Workers': 50,
    'Web3.js': 70,
    'WebAssembly': 50,
    'WebGL': 50,
    'Webpack': 60,
    'WebRTC': 50,
    'WebSockets': 50,
    'Windows': 50,
    'Wireshark': 50,
    'Yarn': 50,
    'YOLO & SSD': 50,
    'Yup': 50,
    'ZeroMQ': 50,
    'zkSync': 45,
    'ZOD': 50,
    'Zoho': 50,
    'Zustand': 60
};
